### ISSUE TITLE
How about reminders for other users

### ISSUE THREAD

**Issue by meaku** [probot/reminders#11]
Hi there,

we really like this feature for probot! 👍 
One feature that would make it even more handy is reminders for other users than `me`. 

Is there any particular reason why it's only working for the user triggering the reminder? 
If not, I'd be happy to work on a PR. I've also found https://github.com/bkeepers/parse-reminder which would need an update too.

**Comment by bkeepers** [comment]
Yes, pull requests would be very welcome! The only reason it doesn't work is because I just wanted to get it working with as little effort as possible.

@mentions and team mentions would be an awesome addition.

**Comment by meaku** [comment]
@bkeepers: I created a pull request for `parse-reminder`. As far as I can tell it should work without modifications of the reminders integration. https://github.com/bkeepers/parse-reminder/pull/5

**Comment by bkeepers** [comment]
/remind meaku to pat him self on the back tomorrow

**Comment by easherma** [comment]
It looks like this was integrated? If so, would be helpful to update the documentation specifying this as a functionality. Happy to do this as a pull request if you'd like.

**Comment by bkeepers** [comment]
@easherma that'd be great!
