### ISSUE TITLE
Guess the timezone of the user setting a reminder

### ISSUE THREAD

**Issue by bkeepers** [probot/reminders#13]
Setting reminders for specific times is challenging because we don't know the timezone of the user. So if I say `/remind me on monday at 9am`, this app currently assumes you mean 9am UTC, which is probably not what you meant.

@jbjonesjr brought up the desire for timezone data at [office hours](https://probot.github.io/community/#office-hours) today and we had a bit of an epiphany: Git stores the users time offset, so if we can fetch a recent commit from a user, we could infer their timezone offset:

```
$ curl -H 'Accept: application/vnd.github.patch' https://api.github.com/repos/probot/probot/commits/5dde8405c5772ce1794c8216b4b6f24860e3d568 | head -n 3
From 5dde8405c5772ce1794c8216b4b6f24860e3d568 Mon Sep 17 00:00:00 2001
From: Brandon Keepers <bkeepers@github.com>
Date: Thu, 2 Nov 2017 20:39:12 -0500
```

We could use search to get the latest commit for a user:
```
$ curl -H 'Accept: application/vnd.github.cloak-preview' \
  https://api.github.com/search/commits\?q\=author:bkeepers\&per_page\=1\&sort\=committer-date\&order\=desc 
```

And then fetch the raw patch above to get the time offset.

**Comment by Stephen-Gates** [comment]
This could be extended to display the reminder date in the local format. I find mm/dd/yyyy confusing as Australia (and others) use dd/mm/yyyy

E.g. this reads as November to me but it's actually April
<img width="427" alt="screenshot 2018-01-12 08 04 06" src="https://user-images.githubusercontent.com/9379524/34849753-3b84b328-f76f-11e7-9311-153c6ca26eeb.png">

An easier fix is to use dd mmm yyyy  e.g. 04 Apr 2018

**Comment by bkeepers** [comment]
Yep, great idea.

**Comment by knrt10** [comment]
@bkeepers successfully getting the timezone. But can you please suggest how to update the timezone to UTC when creating the comment to user?
