### ISSUE TITLE
Reminder config error?

### ISSUE THREAD

**Issue by reelsense** [probot/reminders#14]
The last time the reminder bot worked in one of my repositories was 26 days ago. Did something change or am I doing something wrong?

**Comment by bkeepers** [comment]
@reelsense The app is working for me. You can see a test here: https://github.com/probot/test/issues/27#issuecomment-345590776

Can you tell me the name of the organization or user account that you have the app installed? There is an issue where having a malformed `.github/config.yml` can cause the app not to function without notice (https://github.com/probot/friction/issues/1), and you might be running into that.

**Comment by reelsense** [comment]
https://github.com/MasieroTechGroup

Looking my commit history it looks like the bot stopped working when I added this to `config.yml`.

```
## BOT Reminders
reminders:  
  # Label applied to issues with pending reminders
  label: reminder
##
```

I'm not sure what part causes it to fail.


```
### BOT
# Configuration for request-info - https://github.com/behaviorbot/request-info

# *Required* Comment to reply with
# Can be either a string :
requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/pr!

# Or an array:
requestInfoReplyComment:
  - Ah no! young blade! That was a trifle short!
  - Tell me more !
  - I am sure you can be more effusive


# *OPTIONAL* default titles to check against for lack of descriptiveness
# MUST BE ALL LOWERCASE
requestInfoDefaultTitles:
  - update readme.md
  - updates

# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: needs-more-info

# *OPTIONAL* Only warn about insufficient information on these events type
# Keys must be lowercase. Valid values are 'issue' and 'pullRequest'
requestInfoLabelToAdd:
  pullRequest: true
  issue: true
###


### BOT
# Configuration for update-docs - https://github.com/behaviorbot/update-docs

# Comment to be posted to on PRs that don't update documentation
updateDocsComment: >
  Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation based on your changes.
updateDocsWhiteList:
  - bug
  - fix
  - error
###

## BOT Reminders
reminders:  
  # Label applied to issues with pending reminders
  label: reminder
##
```

It's very possible I'm doing it wrong.

**Comment by bkeepers** [comment]
The error is actually coming from the duplicate `requestInfoReplyComment` key. YAML appears to not like that.

**Comment by reelsense** [comment]
Thank you! I'll remove and test. I'll reopen if I still have problems.
