### ISSUE TITLE
bot is sometimes non responsive

### ISSUE THREAD

**Issue by caarlos0** [probot/reminders#16]
I've seen it happen at least 2 times now.

Latest: https://github.com/caarlos0/dotfiles/pull/331

It happened on different repos.

Maybe the apps is dying for some reason? I would be happy to help if someone can provide logs or something...

Thanks!

**Comment by caarlos0** [comment]
> Is this still relevant? If so, please comment with any updates or addition details.

this is still happen, yes

**Comment by chris48s** [comment]
Unfortunately #27 doesn't seem to have resolved this problem :(

Here is an example from today: https://github.com/DemocracyClub/UK-Polling-Stations/pull/1300 I would expect reminder bot to have posted a confirmation, [like this](https://github.com/DemocracyClub/polling_deploy/issues/108#issuecomment-369961006)

Let me know if there is any additional info I can provide to help debug.

**Comment by chris48s** [comment]
Another example: https://github.com/DemocracyClub/UK-Polling-Stations/pull/1308

The 2 times I have seen this happen it has been when I've attempted to set a reminder on a pull request. I have never seen this happen in an issue. I note that @caarlos0 's example is also a pull request.

Is the `/remind` command definitely supported in pull requests?

**Comment by hiimbex** [comment]
Right now, the app only works on issues because it only has issues permissions:
<img width="716" alt="screen shot 2018-07-02 at 4 00 55 pm" src="https://user-images.githubusercontent.com/13410355/42190301-2ee683fc-7e11-11e8-947d-0589b2e932a1.png">
