### ISSUE TITLE
Handle failure to parse reminder

### ISSUE THREAD

**Issue by bkeepers** [probot/reminders#3]
There's currently a conditional that checks if the reminder parsing returns a result, and stores the reminder if it does. We should also add an `else` that posts a comment to warn the user, and reports the issue to sentry with `robot.log.error` so we can track syntax of commands that fail to parse.

https://github.com/probot/reminders/blob/bf6e72f55b8a85b95e10daa52ae42ff9c2fb50c6/lib/reminders.js#L15

**Comment by simonstaton** [comment]
Working on it now it looks like Phanatic hasn't taken this yet

**Comment by simonstaton** [comment]
Here you go: https://github.com/probot/reminders/pull/7 I can't find any references to sentry so wasn't able to integrate with your client

**Comment by bkeepers** [comment]
Fixed in #7. Thanks @simonstaton
