### ISSUE TITLE
doesn't work on PRs

### ISSUE THREAD

**Issue by derberg** [probot/reminders#38]
Hey, awesome bot but looks like it works on issues only

please take a look:
- works in issue https://github.com/derberg/test/issues/2
- doesn't work in PR: https://github.com/derberg/test/pull/1

**Comment by iamareebjamal** [comment]
This should be reopened as it does not work on PRs

**Comment by flipace** [comment]
I checked this with a fork, and i believe that the permissions for this app must be changed.
When configured correctly (= R/W access for PRs) it properly reacts to the sent comments.

So, apparently this published app is only configured to work with issues, but not prs (you can easily see this on the configuration screen of it as well).

Until this is fixed here, i published the same app with proper permissions: https://github.com/apps/reminders-prs

**Comment by gillesdemey** [comment]
I also believe this should be reopened, as the original issue is not solved :)

**Comment by nomeata** [comment]
Thanks @flipace, using your fork now :-)

Hope this can be fixed with the official one at some point.
