### ISSUE TITLE
Reminder timing off significantly

### ISSUE THREAD

**Issue by C-Saunders** [probot/reminders#40]
Hi! I set a reminder recently and it seemed to run quite a bit later than expected.

I understand that "tomorrow" was parsed in the context of UTC, but the stated date for the reminder and the actual date of the reminder comment were a couple of days different.

<img width="522" alt="screen shot 2018-12-10 at 7 10 58 pm" src="https://user-images.githubusercontent.com/1126917/49772478-6d70e800-fcbb-11e8-90b5-1486d7f9ddf1.png">

**Comment by fharper** [comment]
Did you find any solution?

**Comment by fharper** [comment]
I had the same issue, it was way off to just be a timezone issue. I'm using https://github.com/apps/octo-reminder for now.
